// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGivM5c5M7_YW-O6NDo55IfNu1TL0yt0k',
    appId: '1:761894033314:web:bb540887056b2ded7344fb',
    messagingSenderId: '761894033314',
    projectId: 'grass-hugs',
    authDomain: 'grass-hugs.firebaseapp.com',
    storageBucket: 'grass-hugs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Vw3lnOCJwOTtrzm1Sz649U3hjaK8_wo',
    appId: '1:761894033314:android:6f756bb59d7896a17344fb',
    messagingSenderId: '761894033314',
    projectId: 'grass-hugs',
    storageBucket: 'grass-hugs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS_lDGU8fdZMV9GUlsj7IPyrgG1vcz68U',
    appId: '1:761894033314:ios:7ce49663bba078a77344fb',
    messagingSenderId: '761894033314',
    projectId: 'grass-hugs',
    storageBucket: 'grass-hugs.appspot.com',
    iosBundleId: 'com.grass.hugs.grassHugs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS_lDGU8fdZMV9GUlsj7IPyrgG1vcz68U',
    appId: '1:761894033314:ios:82ab5f502375263e7344fb',
    messagingSenderId: '761894033314',
    projectId: 'grass-hugs',
    storageBucket: 'grass-hugs.appspot.com',
    iosBundleId: 'com.grass.hugs.grassHugs.RunnerTests',
  );
}
